import { LocaleStringsSnapshotIn } from "./locale-strings";

export const enUS: LocaleStringsSnapshotIn = {
  "app-name": "Muse",
  value: "",
  label: "",

  common_button_ok: "",
  common_button_cancel: "",
  common_button_yes: "",
  common_button_no: "",

  "welcome_new-file": "",
  welcome_open: "",
  welcome_recents: "",
  "welcome_recents-clear": "",

  header_display: "",
  "header_display_show-all": "",
  header_display_headfoot: "",
  header_display_content: "",

  toolbar_file: "",
  toolbar_file_save: "",
  "toolbar_file_save-as": "",
  "toolbar_file_auto-save": "",
  toolbar_file_export: "",
  toolbar_file_close: "",
  toolbar_start: "",
  toolbar_start_undo: "",
  toolbar_start_redo: "",
  "toolbar_start_edit-meta": "",
  toolbar_view: "",
  "toolbar_view_one-page": "",
  "toolbar_view_two-page": "",
  toolbar_about: "",
  toolbar_about_help: "",
  toolbar_about_preference: "",

  footer_sizer: "",
  "footer_sizer_fit-width": "",
  "footer_sizer_fit-height": "",

  modal_meta: "",
  modal_meta_title: "",
  modal_meta_subtitle: "",
  modal_meta_author: "",
  modal_meta_mark: "",
  modal_about: "",
  modal_about_license: "",
  modal_about_issues: "",
  modal_about_releases: "",
  modal_about_help: "",
  modal_about_content: "",
  modal_about_special: "",
  modal_preference: "",
  modal_preference_theme: "",
  modal_preference_language: "",
  "modal_preference_export-scale": "",
  modal_preference_auto: "",
  modal_export: "",
  modal_export_path: "",
  modal_export_name: "",
  modal_export_ext: "",
  modal_sure: "",
  modal_sure_message: "",

  "notification_save-fail": "",
  "notification_export-success": "",
};
