import { LocaleStringsSnapshotIn } from "./locale-strings";

export const zhCN: LocaleStringsSnapshotIn = {
  "app-name": "Muse",
  value: "zh-CN",
  label: "简体中文",

  common_button_ok: "确定",
  common_button_cancel: "取消",
  common_button_yes: "是",
  common_button_no: "否",

  "welcome_new-file": "新建",
  welcome_open: "打开",
  welcome_recents: "最近",
  "welcome_recents-clear": "清除",

  header_display: "显示样式",
  "header_display_show-all": "显示全部",
  header_display_headfoot: "隐藏工具栏",
  header_display_content: "仅显示内容",

  toolbar_file: "文件",
  toolbar_file_save: "保存",
  "toolbar_file_save-as": "另存为",
  "toolbar_file_auto-save": "自动保存",
  toolbar_file_export: "导出",
  toolbar_file_close: "关闭",
  toolbar_start: "开始",
  toolbar_start_undo: "撤销",
  toolbar_start_redo: "重做",
  "toolbar_start_edit-meta": "编辑信息",
  toolbar_view: "视图",
  "toolbar_view_one-page": "单页",
  "toolbar_view_two-page": "双页",
  toolbar_about: "关于",
  toolbar_about_help: "帮助",
  toolbar_about_preference: "设置",

  footer_sizer: "显示比例",
  "footer_sizer_fit-width": "适应宽度",
  "footer_sizer_fit-height": "适应高度",

  modal_meta: "编辑元信息",
  modal_meta_title: "标题",
  modal_meta_subtitle: "副标题",
  modal_meta_author: "作者",
  modal_meta_mark: "调号",
  modal_about: "关于",
  modal_about_license: "开源许可",
  modal_about_issues: "错误报告",
  modal_about_releases: "更新日志",
  modal_about_help: "帮助支持",
  modal_about_content:
    "这是一个开源项目，也是我的第一个完整的前端项目。遇到任何问题，或有任何意见建议，欢迎与我联系。",
  modal_about_special: "特别鸣谢：团团子",
  modal_preference: "设置",
  modal_preference_theme: "主题",
  modal_preference_language: "语言",
  "modal_preference_export-scale": "导出比例",
  modal_preference_auto: "自动",
  modal_export: "导出",
  modal_export_path: "路径",
  modal_export_name: "文件名",
  modal_export_ext: "格式",
  modal_sure: "是否保存",
  modal_sure_message: "是否保存对文件的更改？",

  "notification_save-fail": "保存失败",
  "notification_export-success": "导出成功",
};
