export const strings: Record<string, Record<string, string>> = {
  "en-US": {
    appName: "Muse",
    menuFile: "&File",
    menuFileNew: "&New File",
    menuFileOpen: "&Open",
    menuFileOpenrecent: "Open &Recent",
    menuFileOpenrecentClear: "&Clear Recent",
    menuFileSave: "&Save",
    menuFileSaveas: "Save &As",
    menuFileAutosave: "A&uto Save",
    menuFileExit: "&Exit",
    menuHelp: "&Help",
    menuHelpToggledevtools: "&Toggle Develop Tools",
  },
  "zh-CN": {
    appName: "Muse",
    menuFile: "文件(&F)",
    menuFileNew: "新建(&N)",
    menuFileOpen: "打开(&O)",
    menuFileOpenrecent: "打开最近(&R)",
    menuFileOpenrecentClear: "清除最近(&C)",
    menuFileSave: "保存(&S)",
    menuFileSaveas: "另存为(&A)",
    menuFileAutosave: "自动保存(&U)",
    menuFileExit: "退出(&E)",
    menuHelp: "帮助(&H)",
    menuHelpToggledevtools: "切换开发者工具(&T)",
  },
};
